"""Add Created data

Revision ID: 113406e5790e
Revises: c2936ba61458
Create Date: 2019-06-21 14:00:52.206005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '113406e5790e'
down_revision = 'c2936ba61458'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Products', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('Products', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Products', 'updated_at')
    op.drop_column('Products', 'created_at')
    # ### end Alembic commands ###
