"""Product table

Revision ID: 49853a8a3524
Revises: 113406e5790e
Create Date: 2019-07-17 11:20:46.171654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49853a8a3524'
down_revision = '113406e5790e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_pictures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('path', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_pictures')
    # ### end Alembic commands ###
