"""Add sku to  product table

Revision ID: c2936ba61458
Revises: 01f1006c110b
Create Date: 2019-06-21 10:39:34.939140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2936ba61458'
down_revision = '01f1006c110b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Products', sa.Column('sku', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Products', 'sku')
    # ### end Alembic commands ###
